### ISSUE TITLE
Not guids.  Add note at top of readme explaining

### ISSUE THREAD

**Issue by cmawhorter** [dandean/guid#7]
As I'm sure you're well aware, this creates GUID-like strings, and not GUIDs.  It almost certainly will lead to collisions.

The readme needs a note at the top stating this fact.  I can create a pull, if desired.  #3 touches on this.  

The fact that this bills itself as `npm install guid` does the node community a disservice.

**Comment by dandean** [comment]
See 6d5c67757c50169fb23fd23ee0ba794a88e3afb1

**Comment by cmawhorter** [comment]
e_e

Edit:  That should read "This creates GUID-like strings and not GUIDs.  See node-uuid"

**Comment by dandean** [comment]
Good idea! 4b3d5db3393982ea20bc5add1fd121cccfcdb8ab

**Comment by dandean** [comment]
And honestly, I would unplublish this module if there wasn't the risk of breaking builds for people who depend on it.
