### ISSUE TITLE
Generate a guid from a seed?

### ISSUE THREAD

**Issue by Noxalus** [dandean/guid#9]
Hello,

Is it possible to generate a guid from a seed to have the same guid if we use the same seed? 

If no, do you think it would be difficult to do it?

Thank in advance for answers :smile:

**Comment by ghost** [comment]
The numbers here https://github.com/dandean/guid/blob/master/guid.js#L7 should come from your seed instead of Math.random to do something like that. Btw. this repo doesn't seem to be maintained.

**Comment by dandean** [comment]
Yes, this module is deprecated and marked as so in npm. Use node-uuid instead: https://github.com/broofa/node-uuid

`npm install uuid`
